[package]
name = "program_client"
version = "0.1.0"
edition = "2018"

[dependencies.gecko-client]
path = "../../../crates/client"


[dependencies.fuzzer]
path = "../programs/fuzzer"
features = ["no-entrypoint"]
