[package]
name = "gecko-client"
version = "0.5.0"
edition = "2021"
repository = "https://github.com/jjjutla/GeckoFuzz"
license-file = "../../LICENSE"
readme = "../../README.md"
[features]
fuzzing = ["dep:solana-program-test", "dep:honggfuzz", "arbitrary/derive", "quinn-proto/arbitrary"]

[build-dependencies]
anyhow = { version = "1.0.45", features = ["std"], default-features = false }

[dev-dependencies]
pretty_assertions = "1.1.0"

[dependencies]
gecko-test                = { workspace = true }
solana-sdk                   = { workspace = true }
solana-cli-output            = { workspace = true }
solana-transaction-status    = { workspace = true }
solana-account-decoder       = { workspace = true }
anchor-client                = { workspace = true }
spl-token                    = { workspace = true }
spl-associated-token-account = { workspace = true }
tokio                        = { workspace = true }
rand                         = { workspace = true }
serde_json                   = { workspace = true }
serde                        = { workspace = true }
bincode                      = { workspace = true }
borsh                        = { workspace = true }
futures                      = { workspace = true }
fehler                       = { workspace = true }
thiserror                    = { workspace = true }
ed25519-dalek                = { workspace = true }
serial_test                  = { workspace = true }
anyhow                       = { workspace = true }
cargo_metadata               = { workspace = true }
syn                          = { workspace = true }
quote                        = { workspace = true }
heck                         = { workspace = true }
toml                         = { workspace = true }
log                          = { workspace = true }
rstest                       = { workspace = true }
lazy_static                  = { workspace = true }
honggfuzz                    = { version = "0.5.55", optional = true }
arbitrary                    = { version = "1.3.0", optional = true }
solana-program-test          = { version = "1.16.9", optional = true}
quinn-proto                  = { version = "0.9.4", optional = true}
